export const SET_ERROR_INFO = 'SET_ERROR_INFO'
export const PLAY_MUSIC_LIST = 'PLAY_MUSIC_LIST'
export const PLAYING = 'PLAYING'
export const PLAY_LIST = 'PLAY_LIST'
export const PLAY_STATUS = 'PLAY_STATUS'
export const PLAY_MODE_NUM = 'PLAY_MODE_NUM'
